server:
  port: ":50051"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "securepassword"
  name: "taxi_db"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  topics:
    ride_updates: "ride_updates"
    user_notifications: "user_notifications"

jwt:
  secret_key: "supersecretkey"

logging:
  level: "info"

grpc:
  max_connection_age: "2m"
  keepalive_time: "30s"
