apiVersion: apps/v1
kind: Deployment
metadata:
  name: drivers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drivers
  template:
    metadata:
      labels:
        app: drivers
    spec:
      containers:
        - name: drivers-container
          image: docker.io/gamexost/dock_drivers:latest
          ports:
            - containerPort: 8081  # Укажи порт, который использует твой сервис
