apiVersion: v1
kind: Service
metadata:
  name: drivers-service
spec:
  selector:
    app: drivers
  ports:
    - protocol: TCP
      port: 8081       # Внешний порт сервиса
      targetPort: 8081   # Порт контейнера
  type: NodePort
