version: '3.8'

services:
  psql_db:
    image: awak3r/main_db:1.0
    environment:
      POSTGRES_DB: Auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  app:
    image: awak3r/taxi:1.0
    ports:
      - "8080:8080"
    depends_on:
      - psql_db
      - redis_db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  redis_db:
    image: awak3r/redis_db:1.0
    environment:
      REDIS_PASSWORD: secret
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  postgres_data:
  redis_data:
