version: "3.9"

services:
  # === ZOOKEEPER ===
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # === KAFKA ===
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    depends_on:
      - zookeeper

  # === USERS MICROSERVICE ===
  users_server:
    build:
      context: ./USERS
      dockerfile: Dockerfile
    image: yandexgo_proj_users
    container_name: yandexgo_users_server
    ports:
      - "9093:9093"
      - "9094:9094"
      - "9091:9091"
    restart: unless-stopped
    depends_on:
      - kafka  # можно добавить, чтобы kafka поднялась раньше

  swagger-editor-users:
    image: swaggerapi/swagger-editor
    container_name: swagger-users-editor-container
    ports:
      - "8085:8080"

  swagger-ui-users:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui-users-container
    ports:
      - "8087:8080"
    volumes:
      - ./USERS/API/generated/clients/clients.swagger.json:/tmp/clients.swagger.json
    environment:
      - SWAGGER_JSON=/tmp/clients.swagger.json

  # === DRIVERS MICROSERVICE ===
  drivers_server:
    build:
      context: ./DRIVERS
      dockerfile: Dockerfile
    image: yandexgo_proj_drivers
    container_name: yandexgo_drivers_server
    ports:
      - "9095:9095"
      - "9096:9096"
      - "9097:9097"
    restart: unless-stopped
    depends_on:
      - kafka

  swagger-editor-drivers:
    image: swaggerapi/swagger-editor
    container_name: swagger-drivers-editor-container
    ports:
      - "8084:8080"

  swagger-ui-drivers:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui-drivers-container
    ports:
      - "8086:8080"
    volumes:
      - ./DRIVERS/API/generated/drivers/drivers.swagger.json:/tmp/drivers.swagger.json
    environment:
      - SWAGGER_JSON=/tmp/drivers.swagger.json

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8082:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
