/*
 * clients.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: version not set
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"crypto/rsa"
	"fmt"
	"log"
	"net"
	"net/http"
	"strings"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/segmentio/kafka-go"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	pb "github.com/GameXost/YandexGo_proj/USERS/API/generated/clients"
	"github.com/GameXost/YandexGo_proj/USERS/internal/config"
	"github.com/GameXost/YandexGo_proj/USERS/internal/repository"
	server "github.com/GameXost/YandexGo_proj/USERS/internal/server"
	"github.com/GameXost/YandexGo_proj/USERS/internal/services"
)

var publicKey *rsa.PublicKey

func main() {
	ctx := context.Background()

	// 1. Load config
	cfg, err := config.LoadConfig("config/config.yaml")
	if err != nil {
		log.Fatalf("failed to load config: %v", err)
	}

	// 2. Load JWT keys
	publicKey, err := server.LoadPublicKey(cfg.JWT.PublicKeyPath)
	if err != nil {
		log.Fatalf("failed to load public key: %v", err)
	}
	privateKey, err := server.LoadPrivateKey(cfg.JWT.PrivateKeyPath)
	if err != nil {
		log.Fatalf("failed to load private key: %v", err)
	}
	_ = privateKey

	// 3. DB connection
	connStr := fmt.Sprintf(
		"postgres://%s:%s@%s:%d/%s?sslmode=%s",
		cfg.Database.User, cfg.Database.Password, cfg.Database.Host, cfg.Database.Port, cfg.Database.Name, cfg.Database.SSLMode,
	)
	dbpool, err := pgxpool.New(ctx, connStr)
	if err != nil {
		log.Fatalf("Unable to create pool: %v", err)
	}
	defer dbpool.Close()
	log.Println("PGX working")

	// 4. Kafka connection
	kafkaWriter := kafka.NewWriter(kafka.WriterConfig{
		Brokers: cfg.Kafka.Brokers,
		Topic:   cfg.Kafka.Topics.RideUpdates,
	})
	defer kafkaWriter.Close()
	log.Println("Kafka working")

	repo := repository.NewUserRepository(dbpool)
	userService := services.NewUserService(repo, kafkaWriter)

	// --- Kafka consumer ---
	kafkaReader := kafka.NewReader(kafka.ReaderConfig{
		Brokers:  cfg.Kafka.Brokers,
		Topic:    cfg.Kafka.Topics.RideUpdates,
		GroupID:  "user-service",
		MinBytes: 10e3,
		MaxBytes: 10e6,
	})
	go userService.StartKafkaConsumer(ctx, kafkaReader)

	// server up
	sv := &server.UserServer{
		Service: userService,
	}

	// gRPC server up
	grpcServer := grpc.NewServer(
		grpc.UnaryInterceptor(server.AuthInterceptor(publicKey, cfg.Auth.Disabled)),
	)
	pb.RegisterClientServer(grpcServer, sv)
	grpcListener, err := net.Listen("tcp", cfg.Server.Port)
	if err != nil {
		log.Fatalf("Unable to listen on %s: %v", cfg.Server.Port, err)
	}
	go func() {
		log.Printf("GRPC server listening on %s", cfg.Server.Port)
		if err := grpcServer.Serve(grpcListener); err != nil {
			log.Fatalf("Unable to start grpc server: %v", err)
		}
	}()

	// gRPC gateway up
	mux := runtime.NewServeMux(
		runtime.WithIncomingHeaderMatcher(customHeaderMatcher),
	)
	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
	err = pb.RegisterClientHandlerFromEndpoint(ctx, mux, "localhost"+cfg.Server.Port, opts)
	if err != nil {
		log.Fatalf("Unable to register handler: %v", err)
	}

	log.Println("Mux gateway Listening on", cfg.Server.HTTPPort)
	if err := http.ListenAndServe(cfg.Server.HTTPPort, allowCORS(mux)); err != nil {
		log.Fatalf("Unable to listen on %s: %v", cfg.Server.HTTPPort, err)
	}
}

func allowCORS(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Authorization, Content-Type")
		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}
		h.ServeHTTP(w, r)
	})
}

func customHeaderMatcher(key string) (string, bool) {
	switch strings.ToLower(key) {
	case "authorization":
		return "authorization", true
	default:
		return runtime.DefaultHeaderMatcher(key)
	}
}
