apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8082       # Внешний порт сервиса
      targetPort: 8082   # Порт контейнера
  type: NodePort
