/*
USERS Service API

API fir managing users and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the ClientServiceUpdateProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientServiceUpdateProfileRequest{}

// ClientServiceUpdateProfileRequest struct for ClientServiceUpdateProfileRequest
type ClientServiceUpdateProfileRequest struct {
	// uniq id of user
	Id *string `json:"id,omitempty"`
	// user's firstname
	Username *string `json:"username,omitempty"`
	// user's phone number
	Phone *string `json:"phone,omitempty"`
	// user's email address
	Email *string `json:"email,omitempty"`
}

// NewClientServiceUpdateProfileRequest instantiates a new ClientServiceUpdateProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientServiceUpdateProfileRequest() *ClientServiceUpdateProfileRequest {
	this := ClientServiceUpdateProfileRequest{}
	return &this
}

// NewClientServiceUpdateProfileRequestWithDefaults instantiates a new ClientServiceUpdateProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientServiceUpdateProfileRequestWithDefaults() *ClientServiceUpdateProfileRequest {
	this := ClientServiceUpdateProfileRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClientServiceUpdateProfileRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceUpdateProfileRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ClientServiceUpdateProfileRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ClientServiceUpdateProfileRequest) SetId(v string) {
	o.Id = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ClientServiceUpdateProfileRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceUpdateProfileRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ClientServiceUpdateProfileRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ClientServiceUpdateProfileRequest) SetUsername(v string) {
	o.Username = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *ClientServiceUpdateProfileRequest) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceUpdateProfileRequest) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *ClientServiceUpdateProfileRequest) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *ClientServiceUpdateProfileRequest) SetPhone(v string) {
	o.Phone = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ClientServiceUpdateProfileRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceUpdateProfileRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ClientServiceUpdateProfileRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ClientServiceUpdateProfileRequest) SetEmail(v string) {
	o.Email = &v
}

func (o ClientServiceUpdateProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientServiceUpdateProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableClientServiceUpdateProfileRequest struct {
	value *ClientServiceUpdateProfileRequest
	isSet bool
}

func (v NullableClientServiceUpdateProfileRequest) Get() *ClientServiceUpdateProfileRequest {
	return v.value
}

func (v *NullableClientServiceUpdateProfileRequest) Set(val *ClientServiceUpdateProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClientServiceUpdateProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClientServiceUpdateProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientServiceUpdateProfileRequest(val *ClientServiceUpdateProfileRequest) *NullableClientServiceUpdateProfileRequest {
	return &NullableClientServiceUpdateProfileRequest{value: val, isSet: true}
}

func (v NullableClientServiceUpdateProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientServiceUpdateProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
