/*
USERS Service API

API for managing users and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the ClientServiceLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientServiceLocation{}

// ClientServiceLocation struct for ClientServiceLocation
type ClientServiceLocation struct {
	// latitude
	Latitude *float64 `json:"latitude,omitempty"`
	// longitude
	Longitude *float64 `json:"longitude,omitempty"`
}

// NewClientServiceLocation instantiates a new ClientServiceLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientServiceLocation() *ClientServiceLocation {
	this := ClientServiceLocation{}
	return &this
}

// NewClientServiceLocationWithDefaults instantiates a new ClientServiceLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientServiceLocationWithDefaults() *ClientServiceLocation {
	this := ClientServiceLocation{}
	return &this
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *ClientServiceLocation) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceLocation) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *ClientServiceLocation) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *ClientServiceLocation) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *ClientServiceLocation) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceLocation) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *ClientServiceLocation) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *ClientServiceLocation) SetLongitude(v float64) {
	o.Longitude = &v
}

func (o ClientServiceLocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientServiceLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	return toSerialize, nil
}

type NullableClientServiceLocation struct {
	value *ClientServiceLocation
	isSet bool
}

func (v NullableClientServiceLocation) Get() *ClientServiceLocation {
	return v.value
}

func (v *NullableClientServiceLocation) Set(val *ClientServiceLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableClientServiceLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableClientServiceLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientServiceLocation(val *ClientServiceLocation) *NullableClientServiceLocation {
	return &NullableClientServiceLocation{value: val, isSet: true}
}

func (v NullableClientServiceLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientServiceLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


