/*
USERS Service API

API fir managing users and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the ClientServiceRide type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientServiceRide{}

// ClientServiceRide struct for ClientServiceRide
type ClientServiceRide struct {
	// uniq id of the ride
	Id *string `json:"id,omitempty"`
	// user's id
	UserId *string `json:"userId,omitempty"`
	// driver's id
	DriverId      *string                `json:"driverId,omitempty"`
	StartLocation *ClientServiceLocation `json:"startLocation,omitempty"`
	EndLocation   *ClientServiceLocation `json:"endLocation,omitempty"`
	// ride status
	Status *string `json:"status,omitempty"`
	// starting time point
	Timestamp *string `json:"timestamp,omitempty"`
}

// NewClientServiceRide instantiates a new ClientServiceRide object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientServiceRide() *ClientServiceRide {
	this := ClientServiceRide{}
	return &this
}

// NewClientServiceRideWithDefaults instantiates a new ClientServiceRide object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientServiceRideWithDefaults() *ClientServiceRide {
	this := ClientServiceRide{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClientServiceRide) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRide) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ClientServiceRide) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ClientServiceRide) SetId(v string) {
	o.Id = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ClientServiceRide) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRide) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ClientServiceRide) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *ClientServiceRide) SetUserId(v string) {
	o.UserId = &v
}

// GetDriverId returns the DriverId field value if set, zero value otherwise.
func (o *ClientServiceRide) GetDriverId() string {
	if o == nil || IsNil(o.DriverId) {
		var ret string
		return ret
	}
	return *o.DriverId
}

// GetDriverIdOk returns a tuple with the DriverId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRide) GetDriverIdOk() (*string, bool) {
	if o == nil || IsNil(o.DriverId) {
		return nil, false
	}
	return o.DriverId, true
}

// HasDriverId returns a boolean if a field has been set.
func (o *ClientServiceRide) HasDriverId() bool {
	if o != nil && !IsNil(o.DriverId) {
		return true
	}

	return false
}

// SetDriverId gets a reference to the given string and assigns it to the DriverId field.
func (o *ClientServiceRide) SetDriverId(v string) {
	o.DriverId = &v
}

// GetStartLocation returns the StartLocation field value if set, zero value otherwise.
func (o *ClientServiceRide) GetStartLocation() ClientServiceLocation {
	if o == nil || IsNil(o.StartLocation) {
		var ret ClientServiceLocation
		return ret
	}
	return *o.StartLocation
}

// GetStartLocationOk returns a tuple with the StartLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRide) GetStartLocationOk() (*ClientServiceLocation, bool) {
	if o == nil || IsNil(o.StartLocation) {
		return nil, false
	}
	return o.StartLocation, true
}

// HasStartLocation returns a boolean if a field has been set.
func (o *ClientServiceRide) HasStartLocation() bool {
	if o != nil && !IsNil(o.StartLocation) {
		return true
	}

	return false
}

// SetStartLocation gets a reference to the given ClientServiceLocation and assigns it to the StartLocation field.
func (o *ClientServiceRide) SetStartLocation(v ClientServiceLocation) {
	o.StartLocation = &v
}

// GetEndLocation returns the EndLocation field value if set, zero value otherwise.
func (o *ClientServiceRide) GetEndLocation() ClientServiceLocation {
	if o == nil || IsNil(o.EndLocation) {
		var ret ClientServiceLocation
		return ret
	}
	return *o.EndLocation
}

// GetEndLocationOk returns a tuple with the EndLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRide) GetEndLocationOk() (*ClientServiceLocation, bool) {
	if o == nil || IsNil(o.EndLocation) {
		return nil, false
	}
	return o.EndLocation, true
}

// HasEndLocation returns a boolean if a field has been set.
func (o *ClientServiceRide) HasEndLocation() bool {
	if o != nil && !IsNil(o.EndLocation) {
		return true
	}

	return false
}

// SetEndLocation gets a reference to the given ClientServiceLocation and assigns it to the EndLocation field.
func (o *ClientServiceRide) SetEndLocation(v ClientServiceLocation) {
	o.EndLocation = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ClientServiceRide) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRide) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ClientServiceRide) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ClientServiceRide) SetStatus(v string) {
	o.Status = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ClientServiceRide) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRide) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ClientServiceRide) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *ClientServiceRide) SetTimestamp(v string) {
	o.Timestamp = &v
}

func (o ClientServiceRide) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientServiceRide) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.DriverId) {
		toSerialize["driverId"] = o.DriverId
	}
	if !IsNil(o.StartLocation) {
		toSerialize["startLocation"] = o.StartLocation
	}
	if !IsNil(o.EndLocation) {
		toSerialize["endLocation"] = o.EndLocation
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableClientServiceRide struct {
	value *ClientServiceRide
	isSet bool
}

func (v NullableClientServiceRide) Get() *ClientServiceRide {
	return v.value
}

func (v *NullableClientServiceRide) Set(val *ClientServiceRide) {
	v.value = val
	v.isSet = true
}

func (v NullableClientServiceRide) IsSet() bool {
	return v.isSet
}

func (v *NullableClientServiceRide) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientServiceRide(val *ClientServiceRide) *NullableClientServiceRide {
	return &NullableClientServiceRide{value: val, isSet: true}
}

func (v NullableClientServiceRide) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientServiceRide) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
