/*
USERS Service API

API fir managing users and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the ClientServiceRideHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientServiceRideHistoryResponse{}

// ClientServiceRideHistoryResponse struct for ClientServiceRideHistoryResponse
type ClientServiceRideHistoryResponse struct {
	// List of past rides
	Rides []ClientServiceRide `json:"rides,omitempty"`
}

// NewClientServiceRideHistoryResponse instantiates a new ClientServiceRideHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientServiceRideHistoryResponse() *ClientServiceRideHistoryResponse {
	this := ClientServiceRideHistoryResponse{}
	return &this
}

// NewClientServiceRideHistoryResponseWithDefaults instantiates a new ClientServiceRideHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientServiceRideHistoryResponseWithDefaults() *ClientServiceRideHistoryResponse {
	this := ClientServiceRideHistoryResponse{}
	return &this
}

// GetRides returns the Rides field value if set, zero value otherwise.
func (o *ClientServiceRideHistoryResponse) GetRides() []ClientServiceRide {
	if o == nil || IsNil(o.Rides) {
		var ret []ClientServiceRide
		return ret
	}
	return o.Rides
}

// GetRidesOk returns a tuple with the Rides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceRideHistoryResponse) GetRidesOk() ([]ClientServiceRide, bool) {
	if o == nil || IsNil(o.Rides) {
		return nil, false
	}
	return o.Rides, true
}

// HasRides returns a boolean if a field has been set.
func (o *ClientServiceRideHistoryResponse) HasRides() bool {
	if o != nil && !IsNil(o.Rides) {
		return true
	}

	return false
}

// SetRides gets a reference to the given []ClientServiceRide and assigns it to the Rides field.
func (o *ClientServiceRideHistoryResponse) SetRides(v []ClientServiceRide) {
	o.Rides = v
}

func (o ClientServiceRideHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientServiceRideHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rides) {
		toSerialize["rides"] = o.Rides
	}
	return toSerialize, nil
}

type NullableClientServiceRideHistoryResponse struct {
	value *ClientServiceRideHistoryResponse
	isSet bool
}

func (v NullableClientServiceRideHistoryResponse) Get() *ClientServiceRideHistoryResponse {
	return v.value
}

func (v *NullableClientServiceRideHistoryResponse) Set(val *ClientServiceRideHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientServiceRideHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientServiceRideHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientServiceRideHistoryResponse(val *ClientServiceRideHistoryResponse) *NullableClientServiceRideHistoryResponse {
	return &NullableClientServiceRideHistoryResponse{value: val, isSet: true}
}

func (v NullableClientServiceRideHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientServiceRideHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


