/*
USERS Service API

API for managing users and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the ClientServiceDriver type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientServiceDriver{}

// ClientServiceDriver struct for ClientServiceDriver
type ClientServiceDriver struct {
	// current driver's uniq identificator
	Id *string `json:"id,omitempty"`
	// current driver's firstname
	Username *string `json:"username,omitempty"`
	// your driver's phone number
	Phone *string `json:"phone,omitempty"`
	// driver's car model
	CarModel *string `json:"carModel,omitempty"`
	Location *ClientServiceLocation `json:"location,omitempty"`
	// car make
	CarMake *string `json:"carMake,omitempty"`
	// plate number
	CarNumber *string `json:"carNumber,omitempty"`
	// car color
	CarColor *string `json:"carColor,omitempty"`
}

// NewClientServiceDriver instantiates a new ClientServiceDriver object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientServiceDriver() *ClientServiceDriver {
	this := ClientServiceDriver{}
	return &this
}

// NewClientServiceDriverWithDefaults instantiates a new ClientServiceDriver object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientServiceDriverWithDefaults() *ClientServiceDriver {
	this := ClientServiceDriver{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ClientServiceDriver) SetId(v string) {
	o.Id = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ClientServiceDriver) SetUsername(v string) {
	o.Username = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *ClientServiceDriver) SetPhone(v string) {
	o.Phone = &v
}

// GetCarModel returns the CarModel field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetCarModel() string {
	if o == nil || IsNil(o.CarModel) {
		var ret string
		return ret
	}
	return *o.CarModel
}

// GetCarModelOk returns a tuple with the CarModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetCarModelOk() (*string, bool) {
	if o == nil || IsNil(o.CarModel) {
		return nil, false
	}
	return o.CarModel, true
}

// HasCarModel returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasCarModel() bool {
	if o != nil && !IsNil(o.CarModel) {
		return true
	}

	return false
}

// SetCarModel gets a reference to the given string and assigns it to the CarModel field.
func (o *ClientServiceDriver) SetCarModel(v string) {
	o.CarModel = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetLocation() ClientServiceLocation {
	if o == nil || IsNil(o.Location) {
		var ret ClientServiceLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetLocationOk() (*ClientServiceLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given ClientServiceLocation and assigns it to the Location field.
func (o *ClientServiceDriver) SetLocation(v ClientServiceLocation) {
	o.Location = &v
}

// GetCarMake returns the CarMake field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetCarMake() string {
	if o == nil || IsNil(o.CarMake) {
		var ret string
		return ret
	}
	return *o.CarMake
}

// GetCarMakeOk returns a tuple with the CarMake field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetCarMakeOk() (*string, bool) {
	if o == nil || IsNil(o.CarMake) {
		return nil, false
	}
	return o.CarMake, true
}

// HasCarMake returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasCarMake() bool {
	if o != nil && !IsNil(o.CarMake) {
		return true
	}

	return false
}

// SetCarMake gets a reference to the given string and assigns it to the CarMake field.
func (o *ClientServiceDriver) SetCarMake(v string) {
	o.CarMake = &v
}

// GetCarNumber returns the CarNumber field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetCarNumber() string {
	if o == nil || IsNil(o.CarNumber) {
		var ret string
		return ret
	}
	return *o.CarNumber
}

// GetCarNumberOk returns a tuple with the CarNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetCarNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CarNumber) {
		return nil, false
	}
	return o.CarNumber, true
}

// HasCarNumber returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasCarNumber() bool {
	if o != nil && !IsNil(o.CarNumber) {
		return true
	}

	return false
}

// SetCarNumber gets a reference to the given string and assigns it to the CarNumber field.
func (o *ClientServiceDriver) SetCarNumber(v string) {
	o.CarNumber = &v
}

// GetCarColor returns the CarColor field value if set, zero value otherwise.
func (o *ClientServiceDriver) GetCarColor() string {
	if o == nil || IsNil(o.CarColor) {
		var ret string
		return ret
	}
	return *o.CarColor
}

// GetCarColorOk returns a tuple with the CarColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientServiceDriver) GetCarColorOk() (*string, bool) {
	if o == nil || IsNil(o.CarColor) {
		return nil, false
	}
	return o.CarColor, true
}

// HasCarColor returns a boolean if a field has been set.
func (o *ClientServiceDriver) HasCarColor() bool {
	if o != nil && !IsNil(o.CarColor) {
		return true
	}

	return false
}

// SetCarColor gets a reference to the given string and assigns it to the CarColor field.
func (o *ClientServiceDriver) SetCarColor(v string) {
	o.CarColor = &v
}

func (o ClientServiceDriver) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientServiceDriver) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.CarModel) {
		toSerialize["carModel"] = o.CarModel
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.CarMake) {
		toSerialize["carMake"] = o.CarMake
	}
	if !IsNil(o.CarNumber) {
		toSerialize["carNumber"] = o.CarNumber
	}
	if !IsNil(o.CarColor) {
		toSerialize["carColor"] = o.CarColor
	}
	return toSerialize, nil
}

type NullableClientServiceDriver struct {
	value *ClientServiceDriver
	isSet bool
}

func (v NullableClientServiceDriver) Get() *ClientServiceDriver {
	return v.value
}

func (v *NullableClientServiceDriver) Set(val *ClientServiceDriver) {
	v.value = val
	v.isSet = true
}

func (v NullableClientServiceDriver) IsSet() bool {
	return v.isSet
}

func (v *NullableClientServiceDriver) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientServiceDriver(val *ClientServiceDriver) *NullableClientServiceDriver {
	return &NullableClientServiceDriver{value: val, isSet: true}
}

func (v NullableClientServiceDriver) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientServiceDriver) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


