/*
DRIVER Service API

API for managing drivers and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the DriverServiceUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriverServiceUser{}

// DriverServiceUser struct for DriverServiceUser
type DriverServiceUser struct {
	// Unic user's identificator
	Id *string `json:"id,omitempty"`
	// USer's first name
	Username *string `json:"username,omitempty"`
	// contact number
	Phone *string `json:"phone,omitempty"`
}

// NewDriverServiceUser instantiates a new DriverServiceUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriverServiceUser() *DriverServiceUser {
	this := DriverServiceUser{}
	return &this
}

// NewDriverServiceUserWithDefaults instantiates a new DriverServiceUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriverServiceUserWithDefaults() *DriverServiceUser {
	this := DriverServiceUser{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DriverServiceUser) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverServiceUser) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DriverServiceUser) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DriverServiceUser) SetId(v string) {
	o.Id = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *DriverServiceUser) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverServiceUser) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *DriverServiceUser) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *DriverServiceUser) SetUsername(v string) {
	o.Username = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *DriverServiceUser) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverServiceUser) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *DriverServiceUser) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *DriverServiceUser) SetPhone(v string) {
	o.Phone = &v
}

func (o DriverServiceUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriverServiceUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

type NullableDriverServiceUser struct {
	value *DriverServiceUser
	isSet bool
}

func (v NullableDriverServiceUser) Get() *DriverServiceUser {
	return v.value
}

func (v *NullableDriverServiceUser) Set(val *DriverServiceUser) {
	v.value = val
	v.isSet = true
}

func (v NullableDriverServiceUser) IsSet() bool {
	return v.isSet
}

func (v *NullableDriverServiceUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriverServiceUser(val *DriverServiceUser) *NullableDriverServiceUser {
	return &NullableDriverServiceUser{value: val, isSet: true}
}

func (v NullableDriverServiceUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriverServiceUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


