/*
Driver Service API

API for managing drivers and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the DriverServiceStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriverServiceStatusResponse{}

// DriverServiceStatusResponse struct for DriverServiceStatusResponse
type DriverServiceStatusResponse struct {
	// ride status
	Status *bool `json:"status,omitempty"`
	// details
	Message *string `json:"message,omitempty"`
}

// NewDriverServiceStatusResponse instantiates a new DriverServiceStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriverServiceStatusResponse() *DriverServiceStatusResponse {
	this := DriverServiceStatusResponse{}
	return &this
}

// NewDriverServiceStatusResponseWithDefaults instantiates a new DriverServiceStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriverServiceStatusResponseWithDefaults() *DriverServiceStatusResponse {
	this := DriverServiceStatusResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DriverServiceStatusResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverServiceStatusResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DriverServiceStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *DriverServiceStatusResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DriverServiceStatusResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverServiceStatusResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DriverServiceStatusResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DriverServiceStatusResponse) SetMessage(v string) {
	o.Message = &v
}

func (o DriverServiceStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriverServiceStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDriverServiceStatusResponse struct {
	value *DriverServiceStatusResponse
	isSet bool
}

func (v NullableDriverServiceStatusResponse) Get() *DriverServiceStatusResponse {
	return v.value
}

func (v *NullableDriverServiceStatusResponse) Set(val *DriverServiceStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDriverServiceStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDriverServiceStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriverServiceStatusResponse(val *DriverServiceStatusResponse) *NullableDriverServiceStatusResponse {
	return &NullableDriverServiceStatusResponse{value: val, isSet: true}
}

func (v NullableDriverServiceStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriverServiceStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


