/*
Driver Service API

API for managing drivers and ride operations

API version: 2.0
Contact: sergejs.dyldin@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DriverServiceRideRequestsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriverServiceRideRequestsResponse{}

// DriverServiceRideRequestsResponse struct for DriverServiceRideRequestsResponse
type DriverServiceRideRequestsResponse struct {
	// available rides
	RideRequests []DriverServiceRideRequest `json:"rideRequests,omitempty"`
}

// NewDriverServiceRideRequestsResponse instantiates a new DriverServiceRideRequestsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriverServiceRideRequestsResponse() *DriverServiceRideRequestsResponse {
	this := DriverServiceRideRequestsResponse{}
	return &this
}

// NewDriverServiceRideRequestsResponseWithDefaults instantiates a new DriverServiceRideRequestsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriverServiceRideRequestsResponseWithDefaults() *DriverServiceRideRequestsResponse {
	this := DriverServiceRideRequestsResponse{}
	return &this
}

// GetRideRequests returns the RideRequests field value if set, zero value otherwise.
func (o *DriverServiceRideRequestsResponse) GetRideRequests() []DriverServiceRideRequest {
	if o == nil || IsNil(o.RideRequests) {
		var ret []DriverServiceRideRequest
		return ret
	}
	return o.RideRequests
}

// GetRideRequestsOk returns a tuple with the RideRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverServiceRideRequestsResponse) GetRideRequestsOk() ([]DriverServiceRideRequest, bool) {
	if o == nil || IsNil(o.RideRequests) {
		return nil, false
	}
	return o.RideRequests, true
}

// HasRideRequests returns a boolean if a field has been set.
func (o *DriverServiceRideRequestsResponse) HasRideRequests() bool {
	if o != nil && !IsNil(o.RideRequests) {
		return true
	}

	return false
}

// SetRideRequests gets a reference to the given []DriverServiceRideRequest and assigns it to the RideRequests field.
func (o *DriverServiceRideRequestsResponse) SetRideRequests(v []DriverServiceRideRequest) {
	o.RideRequests = v
}

func (o DriverServiceRideRequestsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriverServiceRideRequestsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RideRequests) {
		toSerialize["rideRequests"] = o.RideRequests
	}
	return toSerialize, nil
}

type NullableDriverServiceRideRequestsResponse struct {
	value *DriverServiceRideRequestsResponse
	isSet bool
}

func (v NullableDriverServiceRideRequestsResponse) Get() *DriverServiceRideRequestsResponse {
	return v.value
}

func (v *NullableDriverServiceRideRequestsResponse) Set(val *DriverServiceRideRequestsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDriverServiceRideRequestsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDriverServiceRideRequestsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriverServiceRideRequestsResponse(val *DriverServiceRideRequestsResponse) *NullableDriverServiceRideRequestsResponse {
	return &NullableDriverServiceRideRequestsResponse{value: val, isSet: true}
}

func (v NullableDriverServiceRideRequestsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriverServiceRideRequestsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


