/*
 * Driver Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"github.com/gin-gonic/gin"
)

type LocationAPI struct {
}

// Get /driver/nearby_req
// Get nearby ride requests 
func (api *LocationAPI) GetNearbyRequests(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /driver/location
// Update driver location (streaming) 
func (api *LocationAPI) UpdateLocation(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

