/*
 * Driver Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DriverServiceUser struct {

	// Unic user's identificator
	Id string `json:"id,omitempty"`

	// USer's first name
	Username string `json:"username,omitempty"`

	// contact number
	Phone string `json:"phone,omitempty"`
}
