/*
 * Driver Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DriverServiceLocation struct {

	// Latitude
	Latitude float64 `json:"latitude,omitempty"`

	// Longitude
	Longitude float64 `json:"longitude,omitempty"`
}
