/*
 * Driver Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DriverServiceRide struct {

	// unic id of ride
	Id string `json:"id,omitempty"`

	// unic user's id
	UserId string `json:"userId,omitempty"`

	// unic drivers id
	DriverId string `json:"driverId,omitempty"`

	StartLocation DriverServiceLocation `json:"startLocation,omitempty"`

	EndLocation DriverServiceLocation `json:"endLocation,omitempty"`

	// ride status
	Status string `json:"status,omitempty"`

	// time mark for start point
	Timestamp string `json:"timestamp,omitempty"`
}
