/*
 * DRIVER Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DriverServiceStatusResponse struct {

	// ride status
	Status bool `json:"status,omitempty"`

	// details
	Message string `json:"message,omitempty"`
}
