/*
 * Driver Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DriverServiceLocationUpdateRequest struct {

	// Driver ID
	DriverId string `json:"driverId,omitempty"`

	Location DriverServiceLocation `json:"location,omitempty"`
}
