/*
 * Driver Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DriverServiceRideHistoryResponse struct {

	// previous rides
	Rides []DriverServiceRide `json:"rides,omitempty"`
}
