/*
 * DRIVER Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type DriverServiceUpdateDriverProfileRequest struct {

	// Driver ID
	Id string `json:"id,omitempty"`

	Driver DriverServiceDriver `json:"driver,omitempty"`
}
