/*
 * Driver Service API
 *
 * API for managing drivers and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	pb "github.com/GameXost/YandexGo_proj/DRIVERS/API/generated/drivers"
	sw "github.com/GameXost/YandexGo_proj/DRIVERS/server/go"
)

func main() {
	routes := sw.ApiHandleFunctions{}

	log.Printf("Server started")
	log.Printf("Shit happens")
	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
