services:

  swagger-editor-drivers:
    image: swaggerapi/swagger-editor
    container_name: "swagger-drivers-editor-container"
    ports:
      - "8084:8080"

  swagger-ui-drivers:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-drivers-container"
    ports:
      - "8086:8080"
    volumes:
      - ./API/generated/drivers/drivers.swagger.json:/tmp/drivers.swagger.json
    environment:
      - SWAGGER_JSON=/tmp/drivers.swagger.json
