server:
  port: ":9097"
  http_port: ":9096"

database:
  host: "79.174.85.58"
  port: 5432
  user: "admin"
  password: "secret"
  name: "Auth"
  sslmode: "disable"

redis:
  host: "79.174.85.58"
  port: 6379
  password: "secret"
  db: 0

kafka:
  brokers:
    - "kafka:9092"
  topics:
    rides: "rides_topic"
    user_requests: "user_requests_topic"
    user_notifications: "user_notifications_topic"
    driver_requests: "driver_requests_topic"
    driver_notifications: "driver_notifications_topic"

jwt:
  secret_key: "supersecretkey"
  public_key_path: "config/public_key.pem"
  private_key_path: "config/private_key.pem"

logging:
  level: "info"

grpc:
  max_connection_age: "2m"
  keepalive_time: "30s"

auth:
  disabled: false

prometheus:
  port: "9099"

swagger:
  file: "docs/swagger.json"
