server:
  port: ":9093"

database:
  host: "79.174.85.58"
  port: 5432
  user: "admin"
  password: "secret"
  name: "Auth"
  sslmode: "disable"

redis:
  host: "79.174.85.58"
  port: 6379
  password: "secret"
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  topics:
    ride_updates: "rides"
    user_notifications: "user_notifications"

jwt:
  secret_key: "supersecretkey"
  public_key_path: "config/public_key.pem"
  private_key_path: "config/private_key.pem"

logging:
  level: "info"

grpc:
  max_connection_age: "2m"
  keepalive_time: "30s"
