/*
 * USERS Service API
 *
 * API for managing users and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"github.com/gin-gonic/gin"
)

type RidesAPI struct {
}

// Post /ride/:id/cancel
// Cancel ride 
func (api *RidesAPI) CancelRide(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /ride/:id
// get ride information 
func (api *RidesAPI) GetCurrentRide(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /ride/history
// Get history of last rides 
func (api *RidesAPI) GetRidesHistory(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /ride/request
// request a ride 
func (api *RidesAPI) RequestRide(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

