/*
 * USERS Service API
 *
 * API for managing users and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ClientServiceRide struct {

	// uniq id of the ride
	Id string `json:"id,omitempty"`

	// user's id
	UserId string `json:"userId,omitempty"`

	// driver's id
	DriverId string `json:"driverId,omitempty"`

	StartLocation ClientServiceLocation `json:"startLocation,omitempty"`

	EndLocation ClientServiceLocation `json:"endLocation,omitempty"`

	// ride status
	Status string `json:"status,omitempty"`

	// starting time point
	Timestamp string `json:"timestamp,omitempty"`
}
