/*
 * USERS Service API
 *
 * API for managing users and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ClientServiceStatusResponse struct {

	// Operation success flag
	Status bool `json:"status,omitempty"`

	// Additional details or error message
	Message string `json:"message,omitempty"`
}
