/*
 * USERS Service API
 *
 * API for managing users and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ClientServiceDriver struct {

	// current driver's uniq identificator
	Id string `json:"id,omitempty"`

	// current driver's firstname
	Username string `json:"username,omitempty"`

	// your driver's phone number
	Phone string `json:"phone,omitempty"`

	// driver's car model
	CarModel string `json:"carModel,omitempty"`

	Location ClientServiceLocation `json:"location,omitempty"`

	// car make
	CarMake string `json:"carMake,omitempty"`

	// plate number
	CarNumber string `json:"carNumber,omitempty"`

	// car color
	CarColor string `json:"carColor,omitempty"`
}
