/*
 * USERS Service API
 *
 * API fir managing users and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ClientServiceRideHistoryResponse struct {

	// List of past rides
	Rides []ClientServiceRide `json:"rides,omitempty"`
}
