/*
 * USERS Service API
 *
 * API fir managing users and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ClientServiceRideRequest struct {

	// User's unique identifier
	UserId string `json:"userId,omitempty"`

	StartLocation ClientServiceLocation `json:"startLocation,omitempty"`

	EndLocation ClientServiceLocation `json:"endLocation,omitempty"`
}
