/*
 * USERS Service API
 *
 * API for managing users and ride operations
 *
 * API version: 2.0
 * Contact: sergejs.dyldin@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ClientServiceUser struct {

	// uniq user identificator
	Id string `json:"id,omitempty"`

	// user's firstname
	Username string `json:"username,omitempty"`

	// user's email
	Email string `json:"email,omitempty"`

	// user's phone number
	Phone string `json:"phone,omitempty"`
}
