services:

  swagger-editor-users:
    image: swaggerapi/swagger-editor
    container_name: "swagger-users-editor-container"
    ports:
      - "8085:8080"
    
  swagger-ui-users:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-users-container"
    ports:
      - "8087:8080"
    volumes:
      - ./API/generated/clients/clients.swagger.json:/tmp/clients.swagger.json
    environment:
      - SWAGGER_JSON=/tmp/clients.swagger.json